language: go

go:
    - tip
    - 1.7
    - 1.6

services:
    - redis-server

notifications:
  webhooks: https://hook.bearychat.com/=bw9bk/travis/99011000053f89bfdc98f8a3e08c4167

install: make get-deps
script: go test -v ./...
